services:
  - type: web
    name: pulso-server
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        value: https://pulsopacto.online
      - key: RESEND_API_KEY
        value: re_B9d9iLDM_FRbEse5kTwQJANoN9g8K4YQU
      - key: REQUIRE_EMAIL_VERIFICATION
        value: "true"
